services:
  - type: web
    name: marin
    env: node
    buildCommand: npm run install-all
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Add your other environment variables here
      # - key: DATABASE_URL
      #   value: your-database-url
